# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: item.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='item.proto',
  package='common',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\nitem.proto\x12\x06\x63ommon\"=\n\x07GetItem\x12\n\n\x02id\x18\x01 \x01(\t\x1a&\n\x08Response\x12\x1a\n\x04item\x18\x01 \x01(\x0b\x32\x0c.common.Item\"N\n\x08PostItem\x12\x1a\n\x04item\x18\x01 \x01(\x0b\x32\x0c.common.Item\x1a&\n\x08Response\x12\x1a\n\x04item\x18\x01 \x01(\x0b\x32\x0c.common.Item\"3\n\x08GetItems\x1a\'\n\x08Response\x12\x1b\n\x05items\x18\x01 \x03(\x0b\x32\x0c.common.Item\"\x1f\n\x04Item\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0b\n\x03msg\x18\x02 \x01(\tb\x06proto3')
)




_GETITEM_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='common.GetItem.Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='item', full_name='common.GetItem.Response.item', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=45,
  serialized_end=83,
)

_GETITEM = _descriptor.Descriptor(
  name='GetItem',
  full_name='common.GetItem',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='common.GetItem.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_GETITEM_RESPONSE, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=83,
)


_POSTITEM_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='common.PostItem.Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='item', full_name='common.PostItem.Response.item', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=45,
  serialized_end=83,
)

_POSTITEM = _descriptor.Descriptor(
  name='PostItem',
  full_name='common.PostItem',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='item', full_name='common.PostItem.item', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_POSTITEM_RESPONSE, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=85,
  serialized_end=163,
)


_GETITEMS_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='common.GetItems.Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='items', full_name='common.GetItems.Response.items', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=177,
  serialized_end=216,
)

_GETITEMS = _descriptor.Descriptor(
  name='GetItems',
  full_name='common.GetItems',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[_GETITEMS_RESPONSE, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=165,
  serialized_end=216,
)


_ITEM = _descriptor.Descriptor(
  name='Item',
  full_name='common.Item',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='common.Item.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='msg', full_name='common.Item.msg', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=218,
  serialized_end=249,
)

_GETITEM_RESPONSE.fields_by_name['item'].message_type = _ITEM
_GETITEM_RESPONSE.containing_type = _GETITEM
_POSTITEM_RESPONSE.fields_by_name['item'].message_type = _ITEM
_POSTITEM_RESPONSE.containing_type = _POSTITEM
_POSTITEM.fields_by_name['item'].message_type = _ITEM
_GETITEMS_RESPONSE.fields_by_name['items'].message_type = _ITEM
_GETITEMS_RESPONSE.containing_type = _GETITEMS
DESCRIPTOR.message_types_by_name['GetItem'] = _GETITEM
DESCRIPTOR.message_types_by_name['PostItem'] = _POSTITEM
DESCRIPTOR.message_types_by_name['GetItems'] = _GETITEMS
DESCRIPTOR.message_types_by_name['Item'] = _ITEM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetItem = _reflection.GeneratedProtocolMessageType('GetItem', (_message.Message,), dict(

  Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), dict(
    DESCRIPTOR = _GETITEM_RESPONSE,
    __module__ = 'item_pb2'
    # @@protoc_insertion_point(class_scope:common.GetItem.Response)
    ))
  ,
  DESCRIPTOR = _GETITEM,
  __module__ = 'item_pb2'
  # @@protoc_insertion_point(class_scope:common.GetItem)
  ))
_sym_db.RegisterMessage(GetItem)
_sym_db.RegisterMessage(GetItem.Response)

PostItem = _reflection.GeneratedProtocolMessageType('PostItem', (_message.Message,), dict(

  Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), dict(
    DESCRIPTOR = _POSTITEM_RESPONSE,
    __module__ = 'item_pb2'
    # @@protoc_insertion_point(class_scope:common.PostItem.Response)
    ))
  ,
  DESCRIPTOR = _POSTITEM,
  __module__ = 'item_pb2'
  # @@protoc_insertion_point(class_scope:common.PostItem)
  ))
_sym_db.RegisterMessage(PostItem)
_sym_db.RegisterMessage(PostItem.Response)

GetItems = _reflection.GeneratedProtocolMessageType('GetItems', (_message.Message,), dict(

  Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), dict(
    DESCRIPTOR = _GETITEMS_RESPONSE,
    __module__ = 'item_pb2'
    # @@protoc_insertion_point(class_scope:common.GetItems.Response)
    ))
  ,
  DESCRIPTOR = _GETITEMS,
  __module__ = 'item_pb2'
  # @@protoc_insertion_point(class_scope:common.GetItems)
  ))
_sym_db.RegisterMessage(GetItems)
_sym_db.RegisterMessage(GetItems.Response)

Item = _reflection.GeneratedProtocolMessageType('Item', (_message.Message,), dict(
  DESCRIPTOR = _ITEM,
  __module__ = 'item_pb2'
  # @@protoc_insertion_point(class_scope:common.Item)
  ))
_sym_db.RegisterMessage(Item)


# @@protoc_insertion_point(module_scope)
