# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: light_sensor.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='light_sensor.proto',
  package='common',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x12light_sensor.proto\x12\x06\x63ommon\"W\n\x12GetLightSensorById\x12\n\n\x02id\x18\x01 \x01(\t\x1a\x35\n\x08Response\x12)\n\x0clight_sensor\x18\x01 \x01(\x0b\x32\x13.common.LightSensor\"u\n\x11\x43reateLightSensor\x12)\n\x0clight_sensor\x18\x01 \x01(\x0b\x32\x13.common.LightSensor\x1a\x35\n\x08Response\x12)\n\x0clight_sensor\x18\x01 \x01(\x0b\x32\x13.common.LightSensor\"I\n\x0fGetLightSensors\x1a\x36\n\x08Response\x12*\n\rlight_sensors\x18\x01 \x03(\x0b\x32\x13.common.LightSensor\"g\n\x0bLightSensor\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05value\x18\x03 \x01(\x01\x12\x15\n\rcreation_time\x18\x04 \x01(\x03\x12\x18\n\x10last_update_time\x18\x05 \x01(\x03\x62\x06proto3')
)




_GETLIGHTSENSORBYID_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='common.GetLightSensorById.Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='light_sensor', full_name='common.GetLightSensorById.Response.light_sensor', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=64,
  serialized_end=117,
)

_GETLIGHTSENSORBYID = _descriptor.Descriptor(
  name='GetLightSensorById',
  full_name='common.GetLightSensorById',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='common.GetLightSensorById.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_GETLIGHTSENSORBYID_RESPONSE, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=117,
)


_CREATELIGHTSENSOR_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='common.CreateLightSensor.Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='light_sensor', full_name='common.CreateLightSensor.Response.light_sensor', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=64,
  serialized_end=117,
)

_CREATELIGHTSENSOR = _descriptor.Descriptor(
  name='CreateLightSensor',
  full_name='common.CreateLightSensor',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='light_sensor', full_name='common.CreateLightSensor.light_sensor', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_CREATELIGHTSENSOR_RESPONSE, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=119,
  serialized_end=236,
)


_GETLIGHTSENSORS_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='common.GetLightSensors.Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='light_sensors', full_name='common.GetLightSensors.Response.light_sensors', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=257,
  serialized_end=311,
)

_GETLIGHTSENSORS = _descriptor.Descriptor(
  name='GetLightSensors',
  full_name='common.GetLightSensors',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[_GETLIGHTSENSORS_RESPONSE, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=238,
  serialized_end=311,
)


_LIGHTSENSOR = _descriptor.Descriptor(
  name='LightSensor',
  full_name='common.LightSensor',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='common.LightSensor.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='common.LightSensor.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='common.LightSensor.value', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='creation_time', full_name='common.LightSensor.creation_time', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='last_update_time', full_name='common.LightSensor.last_update_time', index=4,
      number=5, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=313,
  serialized_end=416,
)

_GETLIGHTSENSORBYID_RESPONSE.fields_by_name['light_sensor'].message_type = _LIGHTSENSOR
_GETLIGHTSENSORBYID_RESPONSE.containing_type = _GETLIGHTSENSORBYID
_CREATELIGHTSENSOR_RESPONSE.fields_by_name['light_sensor'].message_type = _LIGHTSENSOR
_CREATELIGHTSENSOR_RESPONSE.containing_type = _CREATELIGHTSENSOR
_CREATELIGHTSENSOR.fields_by_name['light_sensor'].message_type = _LIGHTSENSOR
_GETLIGHTSENSORS_RESPONSE.fields_by_name['light_sensors'].message_type = _LIGHTSENSOR
_GETLIGHTSENSORS_RESPONSE.containing_type = _GETLIGHTSENSORS
DESCRIPTOR.message_types_by_name['GetLightSensorById'] = _GETLIGHTSENSORBYID
DESCRIPTOR.message_types_by_name['CreateLightSensor'] = _CREATELIGHTSENSOR
DESCRIPTOR.message_types_by_name['GetLightSensors'] = _GETLIGHTSENSORS
DESCRIPTOR.message_types_by_name['LightSensor'] = _LIGHTSENSOR
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetLightSensorById = _reflection.GeneratedProtocolMessageType('GetLightSensorById', (_message.Message,), dict(

  Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), dict(
    DESCRIPTOR = _GETLIGHTSENSORBYID_RESPONSE,
    __module__ = 'light_sensor_pb2'
    # @@protoc_insertion_point(class_scope:common.GetLightSensorById.Response)
    ))
  ,
  DESCRIPTOR = _GETLIGHTSENSORBYID,
  __module__ = 'light_sensor_pb2'
  # @@protoc_insertion_point(class_scope:common.GetLightSensorById)
  ))
_sym_db.RegisterMessage(GetLightSensorById)
_sym_db.RegisterMessage(GetLightSensorById.Response)

CreateLightSensor = _reflection.GeneratedProtocolMessageType('CreateLightSensor', (_message.Message,), dict(

  Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), dict(
    DESCRIPTOR = _CREATELIGHTSENSOR_RESPONSE,
    __module__ = 'light_sensor_pb2'
    # @@protoc_insertion_point(class_scope:common.CreateLightSensor.Response)
    ))
  ,
  DESCRIPTOR = _CREATELIGHTSENSOR,
  __module__ = 'light_sensor_pb2'
  # @@protoc_insertion_point(class_scope:common.CreateLightSensor)
  ))
_sym_db.RegisterMessage(CreateLightSensor)
_sym_db.RegisterMessage(CreateLightSensor.Response)

GetLightSensors = _reflection.GeneratedProtocolMessageType('GetLightSensors', (_message.Message,), dict(

  Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), dict(
    DESCRIPTOR = _GETLIGHTSENSORS_RESPONSE,
    __module__ = 'light_sensor_pb2'
    # @@protoc_insertion_point(class_scope:common.GetLightSensors.Response)
    ))
  ,
  DESCRIPTOR = _GETLIGHTSENSORS,
  __module__ = 'light_sensor_pb2'
  # @@protoc_insertion_point(class_scope:common.GetLightSensors)
  ))
_sym_db.RegisterMessage(GetLightSensors)
_sym_db.RegisterMessage(GetLightSensors.Response)

LightSensor = _reflection.GeneratedProtocolMessageType('LightSensor', (_message.Message,), dict(
  DESCRIPTOR = _LIGHTSENSOR,
  __module__ = 'light_sensor_pb2'
  # @@protoc_insertion_point(class_scope:common.LightSensor)
  ))
_sym_db.RegisterMessage(LightSensor)


# @@protoc_insertion_point(module_scope)
