# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import service as _service
from google.protobuf import service_reflection
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import generic_pb2 as generic__pb2
import item_pb2 as item__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='service.proto',
  package='py4mac',
  syntax='proto2',
  serialized_options=_b('\220\001\001'),
  serialized_pb=_b('\n\rservice.proto\x12\x06py4mac\x1a\rgeneric.proto\x1a\nitem.proto2\xb6\x02\n\x07RestApi\x12\x66\n\x07getItem\x12\x0f.common.GetItem\x1a\x18.common.GetItem.Response\"0\xf2\x86\x19,\n\x18\n\x03GET\x12\x0b/items/{id}\x1a\x04\x08\x02\x10\x00\x10\x01*\x0eGet Item by Id\x12_\n\x08getItems\x12\x10.common.GetItems\x1a\x19.common.GetItems.Response\"&\xf2\x86\x19\"\n\x13\n\x03GET\x12\x06/items\x1a\x04\x08\x02\x10\x00\x10\x01*\tGet Items\x12\x62\n\x08postItem\x12\x10.common.PostItem\x1a\x19.common.PostItem.Response\")\xf2\x86\x19%\n\x14\n\x04POST\x12\x06/items\x1a\x04\x08\x02\x10\x00\x10\x01*\x0b\x43reate ItemB\x03\x90\x01\x01')
  ,
  dependencies=[generic__pb2.DESCRIPTOR,item__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DESCRIPTOR._options = None

_RESTAPI = _descriptor.ServiceDescriptor(
  name='RestApi',
  full_name='py4mac.RestApi',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=53,
  serialized_end=363,
  methods=[
  _descriptor.MethodDescriptor(
    name='getItem',
    full_name='py4mac.RestApi.getItem',
    index=0,
    containing_service=None,
    input_type=item__pb2._GETITEM,
    output_type=item__pb2._GETITEM_RESPONSE,
    serialized_options=_b('\362\206\031,\n\030\n\003GET\022\013/items/{id}\032\004\010\002\020\000\020\001*\016Get Item by Id'),
  ),
  _descriptor.MethodDescriptor(
    name='getItems',
    full_name='py4mac.RestApi.getItems',
    index=1,
    containing_service=None,
    input_type=item__pb2._GETITEMS,
    output_type=item__pb2._GETITEMS_RESPONSE,
    serialized_options=_b('\362\206\031\"\n\023\n\003GET\022\006/items\032\004\010\002\020\000\020\001*\tGet Items'),
  ),
  _descriptor.MethodDescriptor(
    name='postItem',
    full_name='py4mac.RestApi.postItem',
    index=2,
    containing_service=None,
    input_type=item__pb2._POSTITEM,
    output_type=item__pb2._POSTITEM_RESPONSE,
    serialized_options=_b('\362\206\031%\n\024\n\004POST\022\006/items\032\004\010\002\020\000\020\001*\013Create Item'),
  ),
])
_sym_db.RegisterServiceDescriptor(_RESTAPI)

DESCRIPTOR.services_by_name['RestApi'] = _RESTAPI

RestApi = service_reflection.GeneratedServiceType('RestApi', (_service.Service,), dict(
  DESCRIPTOR = _RESTAPI,
  __module__ = 'service_pb2'
  ))

RestApi_Stub = service_reflection.GeneratedServiceStubType('RestApi_Stub', (RestApi,), dict(
  DESCRIPTOR = _RESTAPI,
  __module__ = 'service_pb2'
  ))


# @@protoc_insertion_point(module_scope)
