# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import service as _service
from google.protobuf import service_reflection
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import generic_pb2 as generic__pb2
import light_sensor_pb2 as light__sensor__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='service.proto',
  package='lgbsttracker',
  syntax='proto2',
  serialized_options=_b('\220\001\001'),
  serialized_pb=_b('\n\rservice.proto\x12\x0clgbsttracker\x1a\rgeneric.proto\x1a\x12light_sensor.proto2\xcc\x03\n\x07RestApi\x12\x9d\x01\n\x12getLightSensorById\x12\x1a.common.GetLightSensorById\x1a#.common.GetLightSensorById.Response\"F\xf2\x86\x19\x42\n\'\n\x03GET\x12\x1a/sensors/lightsensors/<id>\x1a\x04\x08\x02\x10\x00\x10\x01*\x15Get LightSensor by Id\x12\x8a\x01\n\x0fgetLightSensors\x12\x17.common.GetLightSensors\x1a .common.GetLightSensors.Response\"<\xf2\x86\x19\x38\n\"\n\x03GET\x12\x15/sensors/lightsensors\x1a\x04\x08\x02\x10\x00\x10\x01*\x10Get LightSensors\x12\x93\x01\n\x11\x63reateLightSensor\x12\x19.common.CreateLightSensor\x1a\".common.CreateLightSensor.Response\"?\xf2\x86\x19;\n#\n\x04POST\x12\x15/sensors/lightsensors\x1a\x04\x08\x02\x10\x00\x10\x01*\x12\x43reate LightSensorB\x03\x90\x01\x01')
  ,
  dependencies=[generic__pb2.DESCRIPTOR,light__sensor__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DESCRIPTOR._options = None

_RESTAPI = _descriptor.ServiceDescriptor(
  name='RestApi',
  full_name='lgbsttracker.RestApi',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=67,
  serialized_end=527,
  methods=[
  _descriptor.MethodDescriptor(
    name='getLightSensorById',
    full_name='lgbsttracker.RestApi.getLightSensorById',
    index=0,
    containing_service=None,
    input_type=light__sensor__pb2._GETLIGHTSENSORBYID,
    output_type=light__sensor__pb2._GETLIGHTSENSORBYID_RESPONSE,
    serialized_options=_b('\362\206\031B\n\'\n\003GET\022\032/sensors/lightsensors/<id>\032\004\010\002\020\000\020\001*\025Get LightSensor by Id'),
  ),
  _descriptor.MethodDescriptor(
    name='getLightSensors',
    full_name='lgbsttracker.RestApi.getLightSensors',
    index=1,
    containing_service=None,
    input_type=light__sensor__pb2._GETLIGHTSENSORS,
    output_type=light__sensor__pb2._GETLIGHTSENSORS_RESPONSE,
    serialized_options=_b('\362\206\0318\n\"\n\003GET\022\025/sensors/lightsensors\032\004\010\002\020\000\020\001*\020Get LightSensors'),
  ),
  _descriptor.MethodDescriptor(
    name='createLightSensor',
    full_name='lgbsttracker.RestApi.createLightSensor',
    index=2,
    containing_service=None,
    input_type=light__sensor__pb2._CREATELIGHTSENSOR,
    output_type=light__sensor__pb2._CREATELIGHTSENSOR_RESPONSE,
    serialized_options=_b('\362\206\031;\n#\n\004POST\022\025/sensors/lightsensors\032\004\010\002\020\000\020\001*\022Create LightSensor'),
  ),
])
_sym_db.RegisterServiceDescriptor(_RESTAPI)

DESCRIPTOR.services_by_name['RestApi'] = _RESTAPI

RestApi = service_reflection.GeneratedServiceType('RestApi', (_service.Service,), dict(
  DESCRIPTOR = _RESTAPI,
  __module__ = 'service_pb2'
  ))

RestApi_Stub = service_reflection.GeneratedServiceStubType('RestApi_Stub', (RestApi,), dict(
  DESCRIPTOR = _RESTAPI,
  __module__ = 'service_pb2'
  ))


# @@protoc_insertion_point(module_scope)
