# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api_storage_sensors_service.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import service as _service
from google.protobuf import service_reflection
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import sensors_message_pb2 as sensors__message__pb2
from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from protoc_gen_swagger.options import annotations_pb2 as protoc__gen__swagger_dot_options_dot_annotations__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='api_storage_sensors_service.proto',
  package='lgbsttracker.api.v1',
  syntax='proto3',
  serialized_options=_b('\220\001\001'),
  serialized_pb=_b('\n!api_storage_sensors_service.proto\x12\x13lgbsttracker.api.v1\x1a\x15sensors_message.proto\x1a\x1cgoogle/api/annotations.proto\x1a,protoc-gen-swagger/options/annotations.proto\"^\n\x11\x43reateLightSensor\x12\x0c\n\x04name\x18\x01 \x01(\t\x1a;\n\x08Response\x12/\n\x04item\x18\x01 \x01(\x0b\x32!.lgbsttracker.sensors.LightSensor2\xde\x01\n\x11StorageSensorsApi\x12\xc8\x01\n\x11\x63reateLightSensor\x12&.lgbsttracker.api.v1.CreateLightSensor\x1a/.lgbsttracker.api.v1.CreateLightSensor.Response\"Z\x82\xd3\xe4\x93\x02\'\"\"/storage/v1.0/sensors/lightsensors:\x01*\x92\x41*\x12\x13\x43reate Light Sensor\x1a\x13\x43reate Light SensorB\x03\x90\x01\x01\x62\x06proto3')
  ,
  dependencies=[sensors__message__pb2.DESCRIPTOR,google_dot_api_dot_annotations__pb2.DESCRIPTOR,protoc__gen__swagger_dot_options_dot_annotations__pb2.DESCRIPTOR,])




_CREATELIGHTSENSOR_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='lgbsttracker.api.v1.CreateLightSensor.Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='item', full_name='lgbsttracker.api.v1.CreateLightSensor.Response.item', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=192,
  serialized_end=251,
)

_CREATELIGHTSENSOR = _descriptor.Descriptor(
  name='CreateLightSensor',
  full_name='lgbsttracker.api.v1.CreateLightSensor',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='lgbsttracker.api.v1.CreateLightSensor.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_CREATELIGHTSENSOR_RESPONSE, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=157,
  serialized_end=251,
)

_CREATELIGHTSENSOR_RESPONSE.fields_by_name['item'].message_type = sensors__message__pb2._LIGHTSENSOR
_CREATELIGHTSENSOR_RESPONSE.containing_type = _CREATELIGHTSENSOR
DESCRIPTOR.message_types_by_name['CreateLightSensor'] = _CREATELIGHTSENSOR
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CreateLightSensor = _reflection.GeneratedProtocolMessageType('CreateLightSensor', (_message.Message,), dict(

  Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), dict(
    DESCRIPTOR = _CREATELIGHTSENSOR_RESPONSE,
    __module__ = 'api_storage_sensors_service_pb2'
    # @@protoc_insertion_point(class_scope:lgbsttracker.api.v1.CreateLightSensor.Response)
    ))
  ,
  DESCRIPTOR = _CREATELIGHTSENSOR,
  __module__ = 'api_storage_sensors_service_pb2'
  # @@protoc_insertion_point(class_scope:lgbsttracker.api.v1.CreateLightSensor)
  ))
_sym_db.RegisterMessage(CreateLightSensor)
_sym_db.RegisterMessage(CreateLightSensor.Response)


DESCRIPTOR._options = None

_STORAGESENSORSAPI = _descriptor.ServiceDescriptor(
  name='StorageSensorsApi',
  full_name='lgbsttracker.api.v1.StorageSensorsApi',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=254,
  serialized_end=476,
  methods=[
  _descriptor.MethodDescriptor(
    name='createLightSensor',
    full_name='lgbsttracker.api.v1.StorageSensorsApi.createLightSensor',
    index=0,
    containing_service=None,
    input_type=_CREATELIGHTSENSOR,
    output_type=_CREATELIGHTSENSOR_RESPONSE,
    serialized_options=_b('\202\323\344\223\002\'\"\"/storage/v1.0/sensors/lightsensors:\001*\222A*\022\023Create Light Sensor\032\023Create Light Sensor'),
  ),
])
_sym_db.RegisterServiceDescriptor(_STORAGESENSORSAPI)

DESCRIPTOR.services_by_name['StorageSensorsApi'] = _STORAGESENSORSAPI

StorageSensorsApi = service_reflection.GeneratedServiceType('StorageSensorsApi', (_service.Service,), dict(
  DESCRIPTOR = _STORAGESENSORSAPI,
  __module__ = 'api_storage_sensors_service_pb2'
  ))

StorageSensorsApi_Stub = service_reflection.GeneratedServiceStubType('StorageSensorsApi_Stub', (StorageSensorsApi,), dict(
  DESCRIPTOR = _STORAGESENSORSAPI,
  __module__ = 'api_storage_sensors_service_pb2'
  ))


# @@protoc_insertion_point(module_scope)
