# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: generic.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import descriptor_pb2 as google_dot_protobuf_dot_descriptor__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='generic.proto',
  package='lgbsttracker',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\rgeneric.proto\x12\x0clgbsttracker\x1a google/protobuf/descriptor.proto\"6\n\x18GenericCustomHttpPattern\x12\x0c\n\x04kind\x18\x01 \x01(\t\x12\x0c\n\x04path\x18\x02 \x01(\t\"\x9a\x02\n\x0fGenericHttpRule\x12\x10\n\x08selector\x18\x01 \x01(\t\x12\r\n\x03get\x18\x02 \x01(\tH\x00\x12\r\n\x03put\x18\x03 \x01(\tH\x00\x12\x0e\n\x04post\x18\x04 \x01(\tH\x00\x12\x10\n\x06\x64\x65lete\x18\x05 \x01(\tH\x00\x12\x0f\n\x05patch\x18\x06 \x01(\tH\x00\x12\x38\n\x06\x63ustom\x18\x08 \x01(\x0b\x32&.lgbsttracker.GenericCustomHttpPatternH\x00\x12\x0c\n\x04\x62ody\x18\x07 \x01(\t\x12\x15\n\rresponse_body\x18\x0c \x01(\t\x12:\n\x13\x61\x64\x64itional_bindings\x18\x0b \x03(\x0b\x32\x1d.lgbsttracker.GenericHttpRuleB\t\n\x07pattern*\x82\x02\n\tErrorCode\x12\x12\n\x0eINTERNAL_ERROR\x10\x00\x12\x1b\n\x17TEMPORARILY_UNAVAILABLE\x10\x01\x12\x16\n\x12\x45NDPOINT_NOT_FOUND\x10\x02\x12\x15\n\x11PERMISSION_DENIED\x10\x03\x12\x1a\n\x16REQUEST_LIMIT_EXCEEDED\x10\x04\x12\x0f\n\x0b\x42\x41\x44_REQUEST\x10\x05\x12\x1b\n\x17INVALID_PARAMETER_VALUE\x10\x06\x12\x1b\n\x17RESOURCE_DOES_NOT_EXIST\x10\x07\x12\x11\n\rINVALID_STATE\x10\x08\x12\x1b\n\x17RESOURCE_ALREADY_EXISTS\x10\t:N\n\x04http\x12\x1e.google.protobuf.MethodOptions\x18\xb0\xca\xbc\" \x01(\x0b\x32\x1d.lgbsttracker.GenericHttpRuleb\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_descriptor__pb2.DESCRIPTOR,])

_ERRORCODE = _descriptor.EnumDescriptor(
  name='ErrorCode',
  full_name='lgbsttracker.ErrorCode',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='INTERNAL_ERROR', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TEMPORARILY_UNAVAILABLE', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ENDPOINT_NOT_FOUND', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PERMISSION_DENIED', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='REQUEST_LIMIT_EXCEEDED', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BAD_REQUEST', index=5, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INVALID_PARAMETER_VALUE', index=6, number=6,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RESOURCE_DOES_NOT_EXIST', index=7, number=7,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INVALID_STATE', index=8, number=8,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RESOURCE_ALREADY_EXISTS', index=9, number=9,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=407,
  serialized_end=665,
)
_sym_db.RegisterEnumDescriptor(_ERRORCODE)

ErrorCode = enum_type_wrapper.EnumTypeWrapper(_ERRORCODE)
INTERNAL_ERROR = 0
TEMPORARILY_UNAVAILABLE = 1
ENDPOINT_NOT_FOUND = 2
PERMISSION_DENIED = 3
REQUEST_LIMIT_EXCEEDED = 4
BAD_REQUEST = 5
INVALID_PARAMETER_VALUE = 6
RESOURCE_DOES_NOT_EXIST = 7
INVALID_STATE = 8
RESOURCE_ALREADY_EXISTS = 9

HTTP_FIELD_NUMBER = 72295728
http = _descriptor.FieldDescriptor(
  name='http', full_name='lgbsttracker.http', index=0,
  number=72295728, type=11, cpp_type=10, label=1,
  has_default_value=False, default_value=None,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  serialized_options=None, file=DESCRIPTOR)


_GENERICCUSTOMHTTPPATTERN = _descriptor.Descriptor(
  name='GenericCustomHttpPattern',
  full_name='lgbsttracker.GenericCustomHttpPattern',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='kind', full_name='lgbsttracker.GenericCustomHttpPattern.kind', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='path', full_name='lgbsttracker.GenericCustomHttpPattern.path', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=65,
  serialized_end=119,
)


_GENERICHTTPRULE = _descriptor.Descriptor(
  name='GenericHttpRule',
  full_name='lgbsttracker.GenericHttpRule',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='selector', full_name='lgbsttracker.GenericHttpRule.selector', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='get', full_name='lgbsttracker.GenericHttpRule.get', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='put', full_name='lgbsttracker.GenericHttpRule.put', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='post', full_name='lgbsttracker.GenericHttpRule.post', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='delete', full_name='lgbsttracker.GenericHttpRule.delete', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='patch', full_name='lgbsttracker.GenericHttpRule.patch', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='custom', full_name='lgbsttracker.GenericHttpRule.custom', index=6,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='body', full_name='lgbsttracker.GenericHttpRule.body', index=7,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='response_body', full_name='lgbsttracker.GenericHttpRule.response_body', index=8,
      number=12, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='additional_bindings', full_name='lgbsttracker.GenericHttpRule.additional_bindings', index=9,
      number=11, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='pattern', full_name='lgbsttracker.GenericHttpRule.pattern',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=122,
  serialized_end=404,
)

_GENERICHTTPRULE.fields_by_name['custom'].message_type = _GENERICCUSTOMHTTPPATTERN
_GENERICHTTPRULE.fields_by_name['additional_bindings'].message_type = _GENERICHTTPRULE
_GENERICHTTPRULE.oneofs_by_name['pattern'].fields.append(
  _GENERICHTTPRULE.fields_by_name['get'])
_GENERICHTTPRULE.fields_by_name['get'].containing_oneof = _GENERICHTTPRULE.oneofs_by_name['pattern']
_GENERICHTTPRULE.oneofs_by_name['pattern'].fields.append(
  _GENERICHTTPRULE.fields_by_name['put'])
_GENERICHTTPRULE.fields_by_name['put'].containing_oneof = _GENERICHTTPRULE.oneofs_by_name['pattern']
_GENERICHTTPRULE.oneofs_by_name['pattern'].fields.append(
  _GENERICHTTPRULE.fields_by_name['post'])
_GENERICHTTPRULE.fields_by_name['post'].containing_oneof = _GENERICHTTPRULE.oneofs_by_name['pattern']
_GENERICHTTPRULE.oneofs_by_name['pattern'].fields.append(
  _GENERICHTTPRULE.fields_by_name['delete'])
_GENERICHTTPRULE.fields_by_name['delete'].containing_oneof = _GENERICHTTPRULE.oneofs_by_name['pattern']
_GENERICHTTPRULE.oneofs_by_name['pattern'].fields.append(
  _GENERICHTTPRULE.fields_by_name['patch'])
_GENERICHTTPRULE.fields_by_name['patch'].containing_oneof = _GENERICHTTPRULE.oneofs_by_name['pattern']
_GENERICHTTPRULE.oneofs_by_name['pattern'].fields.append(
  _GENERICHTTPRULE.fields_by_name['custom'])
_GENERICHTTPRULE.fields_by_name['custom'].containing_oneof = _GENERICHTTPRULE.oneofs_by_name['pattern']
DESCRIPTOR.message_types_by_name['GenericCustomHttpPattern'] = _GENERICCUSTOMHTTPPATTERN
DESCRIPTOR.message_types_by_name['GenericHttpRule'] = _GENERICHTTPRULE
DESCRIPTOR.enum_types_by_name['ErrorCode'] = _ERRORCODE
DESCRIPTOR.extensions_by_name['http'] = http
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GenericCustomHttpPattern = _reflection.GeneratedProtocolMessageType('GenericCustomHttpPattern', (_message.Message,), dict(
  DESCRIPTOR = _GENERICCUSTOMHTTPPATTERN,
  __module__ = 'generic_pb2'
  # @@protoc_insertion_point(class_scope:lgbsttracker.GenericCustomHttpPattern)
  ))
_sym_db.RegisterMessage(GenericCustomHttpPattern)

GenericHttpRule = _reflection.GeneratedProtocolMessageType('GenericHttpRule', (_message.Message,), dict(
  DESCRIPTOR = _GENERICHTTPRULE,
  __module__ = 'generic_pb2'
  # @@protoc_insertion_point(class_scope:lgbsttracker.GenericHttpRule)
  ))
_sym_db.RegisterMessage(GenericHttpRule)

http.message_type = _GENERICHTTPRULE
google_dot_protobuf_dot_descriptor__pb2.MethodOptions.RegisterExtension(http)

# @@protoc_insertion_point(module_scope)
