# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lightsensor_message.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='lightsensor_message.proto',
  package='lightsensor',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x19lightsensor_message.proto\x12\x0blightsensor\"g\n\x0bLightSensor\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05value\x18\x03 \x01(\x01\x12\x15\n\rcreation_time\x18\x04 \x01(\x03\x12\x18\n\x10last_update_time\x18\x05 \x01(\x03\x62\x06proto3')
)




_LIGHTSENSOR = _descriptor.Descriptor(
  name='LightSensor',
  full_name='lightsensor.LightSensor',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='lightsensor.LightSensor.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='lightsensor.LightSensor.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='lightsensor.LightSensor.value', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='creation_time', full_name='lightsensor.LightSensor.creation_time', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='last_update_time', full_name='lightsensor.LightSensor.last_update_time', index=4,
      number=5, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=42,
  serialized_end=145,
)

DESCRIPTOR.message_types_by_name['LightSensor'] = _LIGHTSENSOR
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LightSensor = _reflection.GeneratedProtocolMessageType('LightSensor', (_message.Message,), dict(
  DESCRIPTOR = _LIGHTSENSOR,
  __module__ = 'lightsensor_message_pb2'
  # @@protoc_insertion_point(class_scope:lightsensor.LightSensor)
  ))
_sym_db.RegisterMessage(LightSensor)


# @@protoc_insertion_point(module_scope)
