# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sensors_service.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import light_sensor_pb2 as light__sensor__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='sensors_service.proto',
  package='lgbsttracker',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x15sensors_service.proto\x12\x0clgbsttracker\x1a\x12light_sensor.proto2\x89\x02\n\x0eSensorsService\x12U\n\x12getLightSensorById\x12\x1a.common.GetLightSensorById\x1a#.common.GetLightSensorById.Response\x12L\n\x0fgetLightSensors\x12\x17.common.GetLightSensors\x1a .common.GetLightSensors.Response\x12R\n\x11\x63reateLightSensor\x12\x19.common.CreateLightSensor\x1a\".common.CreateLightSensor.Responseb\x06proto3')
  ,
  dependencies=[light__sensor__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_SENSORSSERVICE = _descriptor.ServiceDescriptor(
  name='SensorsService',
  full_name='lgbsttracker.SensorsService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=60,
  serialized_end=325,
  methods=[
  _descriptor.MethodDescriptor(
    name='getLightSensorById',
    full_name='lgbsttracker.SensorsService.getLightSensorById',
    index=0,
    containing_service=None,
    input_type=light__sensor__pb2._GETLIGHTSENSORBYID,
    output_type=light__sensor__pb2._GETLIGHTSENSORBYID_RESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='getLightSensors',
    full_name='lgbsttracker.SensorsService.getLightSensors',
    index=1,
    containing_service=None,
    input_type=light__sensor__pb2._GETLIGHTSENSORS,
    output_type=light__sensor__pb2._GETLIGHTSENSORS_RESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='createLightSensor',
    full_name='lgbsttracker.SensorsService.createLightSensor',
    index=2,
    containing_service=None,
    input_type=light__sensor__pb2._CREATELIGHTSENSOR,
    output_type=light__sensor__pb2._CREATELIGHTSENSOR_RESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SENSORSSERVICE)

DESCRIPTOR.services_by_name['SensorsService'] = _SENSORSSERVICE

# @@protoc_insertion_point(module_scope)
