# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sensors_message.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='sensors_message.proto',
  package='lgbsttracker.sensors',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x15sensors_message.proto\x12\x14lgbsttracker.sensors\x1a\x1fgoogle/protobuf/timestamp.proto\"\x94\x01\n\x0bLightSensor\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x02\x12\x31\n\rcreation_time\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x35\n\x11last_updated_time\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestampb\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])




_LIGHTSENSOR = _descriptor.Descriptor(
  name='LightSensor',
  full_name='lgbsttracker.sensors.LightSensor',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='lgbsttracker.sensors.LightSensor.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='lgbsttracker.sensors.LightSensor.value', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='creation_time', full_name='lgbsttracker.sensors.LightSensor.creation_time', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='last_updated_time', full_name='lgbsttracker.sensors.LightSensor.last_updated_time', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=81,
  serialized_end=229,
)

_LIGHTSENSOR.fields_by_name['creation_time'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_LIGHTSENSOR.fields_by_name['last_updated_time'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
DESCRIPTOR.message_types_by_name['LightSensor'] = _LIGHTSENSOR
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LightSensor = _reflection.GeneratedProtocolMessageType('LightSensor', (_message.Message,), dict(
  DESCRIPTOR = _LIGHTSENSOR,
  __module__ = 'sensors_message_pb2'
  # @@protoc_insertion_point(class_scope:lgbsttracker.sensors.LightSensor)
  ))
_sym_db.RegisterMessage(LightSensor)


# @@protoc_insertion_point(module_scope)
