name: Test
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.x
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: Install Python 3.x dependencies
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install tox codecov
    - name: Test with tox
      run: tox -v
    - name: Publish code coverage
      run: codecov --token ${{ secrets.CODECOV_TOKEN }}
