name: Test
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.x
      uses: actions/setup-python@v1
      with:
        python-version: '3.7.4'
    - name: install pgsql utilities
      run: |
        sudo apt-get install libpq-dev
    - name: Install Python 3.x dependencies
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install -r requirements.txt
    - name: Test with tox
      run: |
        export CODECOV_TOKEN=${{ secrets.CODECOV_TOKEN }}
        make test
        codecov
